/*
 *  error.h
 *  XMLutils
 *
 *  Created by andrew on 6/11/07.
 *  Copyright 2007 __MyCompanyName__. All rights reserved.
 *
 */

// Custom error codes
#define REQUIRES_IGOR_504				1 + FIRST_XOP_ERR
#define XMLDOC_PARSE_ERROR				2 + FIRST_XOP_ERR
#define XPATH_CONTEXT_CREATION_ERROR	3 + FIRST_XOP_ERR
#define FAILED_TO_REGISTER_NAMESPACE	4 + FIRST_XOP_ERR
#define UNABLE_TO_EVAL_XPATH_EXPR		5 + FIRST_XOP_ERR
#define NULL_STRING_HANDLE				6 + FIRST_XOP_ERR
#define XPATH_COMPILE_ERROR				7 + FIRST_XOP_ERR
#define XML_COULDNT_SAVE				8 + FIRST_XOP_ERR
#define ERR_ALTERING_TREE				9 + FIRST_XOP_ERR
#define FILEID_DOESNT_EXIST				10 + FIRST_XOP_ERR
#define COULDNT_CREATE_XMLDOC			11 + FIRST_XOP_ERR
#define COULDNT_CREATE_NODE				12 + FIRST_XOP_ERR
#define INVALID_NODE_NAME				13 + FIRST_XOP_ERR
#define XML_PARSERCTXT_ERROR			14 + FIRST_XOP_ERR
#define XMLDOC_NOTVALIDATED				15 + FIRST_XOP_ERR
#define XMLSCHEMA_NOT_VALID				16 + FIRST_XOP_ERR
#define SCHEMA_CONTEXT_CREATION_ERROR				17 + FIRST_XOP_ERR


